### ISSUE TITLE
OpenAI服务器访问超时或未知类型错误

### ISSUE THREAD

**Issue by Harronzayn** [Jiashisoft/chatglm_PHP#1]
想试试本地部署一直没成功

`<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function curl_init() in D:\software\phpstudy_pro\WWW\ai.com\stream.php:8
Stack trace:
#0 {main}
  thrown in <b>D:\software\phpstudy_pro\WWW\ai.com\stream.php</b> on line <b>8</b><br />`

报错好像是说curl_init() 函数未定义,可能是缺少curl扩展?找了半天也没找到phpstudy环境怎么解决这个问题

**Comment by Jiashisoft** [comment]
这个应该是因为新版php 7~8默认不启用curl导致的，可以在phpstudy环境 软件管理里下载一下老版本 5.6.9nts，然后在网站管理的php版本那里切换下就好了😊
![phpsoft](https://github.com/user-attachments/assets/284ac248-83c1-4010-af01-c3e19e8ea203)
![phpver](https://github.com/user-attachments/assets/b4ba3a7f-33f5-4c20-b7d8-639ad85bab73)
